# frozen_string_literal: true

source "https://rubygems.org"

gem 'activerecord', '>= 8.1.3.1'
gem 'activesupport', '>= 8.1.3.1'
gem 'sqlite3', '>= 2.9.6'
gem 'irb', '>= 1.18'

group :test do
  gem 'minitest', '~> 6.0.6'
end

gem "sinatra", "~> 4.2.1"
gem "puma", "~> 8.0.2"

gem "rackup", "~> 2.3"
