# frozen_string_literal: true

source "https://rubygems.org"

gem 'activerecord', '>= 8.1.3.1'
gem 'activesupport', '>= 8.1.3.1'
gem 'sqlite3', '>= 2.9.6'

group :test do
  gem 'minitest', '~> 5.0'
end
