# frozen_string_literal: true

source "https://rubygems.org"

gem 'activerecord', '>= 8.1.3.1'
gem 'activesupport', '>= 8.1.3.1'
gem 'sqlite3', '>= 2.9.6'
gem 'irb', '>= 1.0'   # rake console 交互式控制台(Ruby 4.0 起不再是默认 gem)

group :test do
  gem 'minitest', '~> 5.0'
end
